### PR TITLE
Fix for missing VERSION

### PR DESCRIPTION
**Pull request by Wenlin88**

### CODE REVIEW

**Comment by Wenlin88** [comment]
This commit fixes #4

**Comment by khazhyk** [comment]
Is this project completely dead? I see the main repo gets commits but that this component can't even be installed is odd

**Comment by WayneKeenan** [comment]
Lacking Windows build infrastructure.

**Comment by WayneKeenan** [comment]
There are a lot of whitespace changes and an unexpected file header added.

**Pull request closed without merging**
